import type { Metadata } from "next";
import { Inter, Montserrat } from "next/font/google";
import "@mantine/core/styles.css";
import "./globals.css";
import { ColorSchemeScript, MantineProvider } from "@mantine/core";

const inter = Inter({ subsets: ["latin"] });
const montserrat = Montserrat({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript forceColorScheme="dark"/>
      </head>
      <body className={montserrat.className}>
        <MantineProvider forceColorScheme="dark">
          {children}
        </MantineProvider>
      </body>
    </html>
  );
}
